### Create a transfers
POST {{URL_END_POINT}}/transfers
Content-Type: application/json

{
  "from_account_id": 1,
  "to_account_id": 2,
  "amount": 100,
  "currency": "CAD"
}

### Create a transfers
POST {{URL_END_POINT}}/accounts
Content-Type: application/json

{
  "owner": "wpcsjp",
  "currency": "EUR"
}

### Create an user
POST {{URL_END_POINT}}/users
Content-Type: application/json

{
  "username": "Hien3",
  "full_name": "Hien Pham",
  "email": "hien3@gmail.com",
  "password": "secret"
}